source/14_django/myproject/article/urls.py
from django.urls import path
from . import views
'''
/article/ => article_list
/article/new => article추가(article_new)
/article/1/detail => 1번 article 상세보기(article_detail)
/article/1/edit => 1번 article 수정(article_edit)
/article/1/delete => 1번 article 삭제(article_delete)
'''
app_name = "article"
urlpatterns = [
  path("", views.article_list, name="list"),
  path("new/", views.article_new, name="new"),
  path("<int:pk>/detail", views.article_detail, name='detail'),
  path("<int:pk>/edit/", views.article_edit, name="edit"),
  path("<int:pk>/delete/", views.article_delete, name="delete"),
]

source/14_django/myproject/blog/urls.py
from django.urls import path, register_converter
from . import views
from .converters import CodeConverter

register_converter(CodeConverter, "dddd")

app_name  = "blog" # 앱이름 사용
urlpatterns = [
    path("", views.index, name="index"),
    # localhost:8000/blog/1
    # path("<int:post_id>/", views.detail, name="detail") # int 컨버터를 사용
    path("<dddd:post_id>/", views.detail, name="detail"),
    path("json/", views.json_test, name="json"),
    path("excel/", views.excel_download, name="excel"),
    path("csv/", views.pandas_csv_download, name="csv"),
    path("csvexcel/", views.pandas_excel_download, name='csvexcel'),
    path("redirect1/", views.get_redirect1, name='redirect1'),
    path("redirect2/", views.get_redirect2, name='redirect2'),
]

source/14_django/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", lambda r : redirect("blog:index")),
    path("blog/", include("blog.urls")),
    path("book/", include("book.urls")),
    path("article/", include("article.urls")),
    # path("file/", include("filetest.urls")),
    path("accounts/", include("accounts.urls")),
]
# 사용자가 업로그한 파일(MEDIA_ROOT)을 url(MEDIA_URL)과 연결
# 장고는 static은 자동 연결해 주나, media는 개발자가 연결
from django.conf.urls.static import static
from . import settings
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

source/14_django/myproject/article/models.py
import os.path
from django.db import models
import time
from datetime import datetime
from django.urls import reverse
from myproject import settings
from django.shortcuts import get_object_or_404
STATUS_CHOICES = (
  ('d', 'Draft'),
  ('p', 'Published'),
  ('w', 'Withdrawn'),
)
def article_photo_path(instance, filename):
  now = datetime.now()
  timestamp = int(time.time() * 1000)  # 밀리초 단위 타임스탬프 생성
  return f"article/{now.strftime('%Y%m%d')}/{timestamp}_{filename}"
class Article(models.Model):
  title = models.CharField(verbose_name='기사제목', max_length=100)
  body  = models.TextField(verbose_name='기사본문')
  status = models.CharField(max_length=1, choices=STATUS_CHOICES)
  #photo = models.ImageField(blank=True, upload_to='article/%Y/%m/%d')
  # pip install pillow
  photo = models.ImageField(blank=True, upload_to=article_photo_path)

  def __str__(self):
    return self.title

  def get_absolute_url(self):
    # return reverse('article:list')
    return  reverse('article:detail', args=[self.id])

  def delete(self, *args, **kwargs):
    if self.photo:
      # 파일 첨부 했으면 지워
      file_path = os.path.join(settings.MEDIA_ROOT, str(self.photo))
      print(file_path, '파일 지운다')
      if os.path.exists(file_path):
        os.remove(file_path)
    super().delete(args, kwargs)

  def save(self, *args, **kwargs):
    if self.pk: # 저장된 내용을 수정하는지 여부?
      old_instance = get_object_or_404(Article, pk=self.pk)
      if old_instance.photo and old_instance.photo != self.photo:
        old_file_path = os.path.join(settings.MEDIA_ROOT,
                                     str(old_instance.photo))
        if os.path.exists(old_file_path):
          os.remove(old_file_path)
    super().save(*args, **kwargs)

source/14_django/myproject/article/views.py
from django.views.generic import ListView, CreateView
from django.views.generic import DetailView, UpdateView,DeleteView
from article.models import Article
from django.urls import reverse_lazy

# Create your views here.
article_list =ListView.as_view(model=Article)
article_new = CreateView.as_view(model=Article, fields='__all__')
article_detail = DetailView.as_view(model=Article)
article_edit = UpdateView.as_view(model=Article, fields='__all__')
article_delete = DeleteView.as_view(model=Article,
                                    success_url=reverse_lazy('article:list'))

source/14_django/myproject/article/templates/article/article_confirm_delete.html
{% extends "base.html" %}

{% block title %}책 등록{% endblock %}

{% block content %}
<div class="container-fluid py-5">
  <h1 class="display-5 fw-bold">삭제 확인</h1>
  <p class="col-md-8 fs-4">정말로 "{{ object }}" 항목을 삭제하시겠습니까?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input class="btn btn-primary btn-lg" type="submit" value="삭제">
    <input  class="btn btn-primary btn-lg" type="button" onclick="location='{{object.get_absolute_url}}'" value="취소">
  </form>
</div>
{% endblock %}

source/14_django/myproject/article/templates/article/article_detail.html
{% extends "base.html" %}

{% block title %}기사 등록{% endblock %}

{% block content %}
  <h2>{{article.id}}.{{article.title}}</h2>
  <p>
    {{article.body | linebreaks }} <!-- 줄바꿈을 br태그로 교체 필터-->
    - status:
    {% if article.status == 'd' %}
      <b>Draft</b>
    {% elif article.status == 'p' %}
      <b>published</b>
    {% else %}
      <b>Withdrawn</b>
    {% endif %}
    <br>
    {% if article.photo %}
      <img src="/media/{{article.photo}}" width="200">
      <img src="{{article.photo.url}}" width="200">
    {% else %}
      <img src="/static/img/noImg.png">
      {% load static %}
      <img src="{% static 'img/noImg.png' %}">
    {% endif %}
  </p>
  <p>
    <a href="{% url 'article:list' %}">[목록]</a>
    <a href="{% url 'article:edit' article.id %}">[수정]</a>
    <a href="{% url 'article:delete' article.id %}">[삭제]</a>
  </p>
{% endblock %}

source/14_django/myproject/article/templates/article/article_form.html
{% extends "base.html" %}

{% block title %}기사 등록{% endblock %}

{% block content %}
  <form action="" method="post" enctype="multipart/form-data">
   {% csrf_token %}
   <table class="table">
     {{form.as_table}}
     <tr>
      <td colspan="2" class="text-center">
       <input type="submit" value="등록">
       <input type="button" value="목록"
       onclick="location='{% url 'article:list'%}'">
      </td>
     </tr>
   </table>
  </form>
{% endblock %}

source/14_django/myproject/article/templates/article/article_list.html
{% extends "base.html" %}

{% block title %}article List{% endblock %}

{% block content %}
 <h2>article List</h2>
  {% for article in article_list %}
    <li>
       {{article.id}}.{{article.title}} / {{article.status}}
        <a href="{% url 'article:detail' article.id %}">[상세]</a>
        <a href="{% url 'article:edit' article.id %}">[수정]</a>
        <a href="{% url 'article:delete' article.id %}">[삭제]</a>
    </li>
  {% empty %}
     <p>기사 목록이 없습니다</p>
  {% endfor %}
  <a href="{% url 'article:new' %}">[article 추가]</a>
{% endblock  %}