source/14_django/ch03_orm/blog/urls.py
from django.urls import path, register_converter
from . import views
from .converters import CodeConverter
register_converter(CodeConverter, "dddd")
app_name = "blog"
urlpatterns = [
  path("", views.index, name="index"),
  # localhost:8000/blog/2000
  #path("<int:post_id>/", views.detail, name='detail'), # int 컨버터를 사용
  path("<dddd:post_id>/", views.detail, name="detail"),
  path("json/", views.json_test, name="json"),
  path("excel/",views.excel_download, name="excel"),
  path("csv/",  views.pandas_csv_download, name='csv'),
  path("csvexcel/", views.pandas_excel_download, name="csvexcel"),
  path("redirect1/", views.get_redirect1, name="redirect1"),
  path("redirect2/", views.get_redirect2, name="redirect2"),
]

source/14_django/ch03_orm/ch03/urls.py
from django.contrib import admin
from django.urls import path
from student import views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name='index'),
]

source/14_django/ch03_orm/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", lambda r : redirect("blog:index")),
    path("blog/", include("blog.urls")),
]

source/14_django/ch03_orm/blog/models.py
from django.db import models
import re
from django.forms import ValidationError
REGION_CHOICE = (
  ("Europe","유럽"),
  ("Asia","아시아"),
  ("Africa","아프리카"),
  ("Oceania","오세아니아"),
  ("America","아메리카"),
)
def lnglat_validator(value):
  if not re.match(r'(\d+\.?\d*),(\d+\.?\d*)', value):
    raise ValidationError('Invalid LngLat. ex:38,125')
class Tag(models.Model):
  name = models.CharField(max_length=50, unique=True)
  def __str__(self):
    return self.name

class Post(models.Model): # 테이블명 : blog_post
  # id = models.AutoField(primary_key=True) PK가 없을 경우 자동 생성
  title = models.CharField(verbose_name="제목",
                           max_length=100) # 최대 길이 반드시 지정 VARCHAR 타입
  content = models.TextField("본문") # 최대 길이 제한이 없음 CLOB, TEXT 타입
  create_at = models.DateField(auto_now_add=True)
  update_at = models.DateTimeField(auto_now=True)
  region = models.CharField(verbose_name="지역",
                            max_length=20,
                            choices=REGION_CHOICE,
                            default='Asia')
  lnglat = models.CharField(verbose_name="경,위도",
                            max_length=100,
                            blank=True,
                            null=True,
                            help_text="경도,위도 포맷",
                            validators=[lnglat_validator]) # 38.5,125.4125
  url = models.URLField(blank=True, null=True)
  tags = models.ManyToManyField("Tag")

  def __str__(self):
    return "제목:{} - {}작성, {:%Y-%m-%d %p %I:%M:%S} 최종수정".format(self.title,
                                                               self.create_at,
                                                               self.update_at)
  class Meta:
    ordering = ['-update_at']

class Comment(models.Model):
  # id = models.AutoField(primary_key=True)
  post = models.ForeignKey(to=Post, # "Post"
                           on_delete=models.CASCADE)
  author = models.CharField(verbose_name="이름", max_length=20)
  message  =models.TextField(verbose_name="댓글")
  create_at = models.DateField(auto_now_add=True)
  update_at = models.DateTimeField(auto_now=True)
  def __str__(self):
    return "{}({}작성)".format(self.message, self.author)
  class Meta:
    ordering = ['-create_at', '-update_at']

source/14_django/ch03_orm/student/models.py
from django.db import models

class Student(models.Model): # 테이블명: 앱명_클래스명(student_student)
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)
    major = models.CharField(max_length=100, null=True)
    age = models.IntegerField(default=0)
    grade = models.IntegerField(default=1)
    def __str__(self):
        return " {}. {} ({} {}학년 {}살)".format(self.id,
                                              self.name,
                                              self.major,
                                              self.grade,
                                              self.age)

source/14_django/ch03_orm/articles/views.py
from django.shortcuts import render

# Create your views here.

source/14_django/ch03_orm/blog/views.py
from django.http import HttpResponse, Http404, JsonResponse
from django.shortcuts import render, get_object_or_404
from .models import Post

def index(request):
  post_list = Post.objects.all()
  # output = '<br>'.join([post.__str__() for post in post_list])
  # print(output)
  # return HttpResponse("<h1>Welcome Page</h1>" + output)
  return render(request,
                'blog/index.html',
                {'post_list':post_list})

def detail(request, post_id):
  # try:
  #   post = Post.objects.get(pk=post_id)
  # except Post.DoesNotExist:
  #   raise Http404("Post does not exist")
  post = get_object_or_404(Post, pk=post_id)
  # return HttpResponse(post.__str__())
  return render(request,
                'blog/detail.html',
                {'post':post})
def json_test(request):
  data = {
    'name':'hong Gildong',
    'age':22,
    'address':'서울시 관악구'
  }
  return JsonResponse(data,
                      json_dumps_params={
                        'ensure_ascii':False # 한글 깨지지 않으려고
                      })

def excel_download(request):
  filename = 'myproject.xlsx'
  with open(filename, 'rb') as f:
    response = HttpResponse(f, content_type='application/vnd.ms-excel')
    response['Content-Disposition']="attachment; filename={}".format(filename)
  return response

import pandas as pd
from io import StringIO, BytesIO
from urllib.parse import quote
def pandas_csv_download(request):
  df = pd.DataFrame([
    [100,90,80],
    [100,99,88],
    [99, 91,79],
  ], columns=['하나','둘','셋'])
  io = StringIO() # 스트링 버퍼
  df.to_csv(io, index=None)
  io.seek(0)
  filename = quote('pandas_csv.csv')
  response = HttpResponse(io, content_type='text/csv')
  response['Content-Disposition'] = "attachment; filename={}".format(filename)
  return response

def pandas_excel_download(request):
  df = pd.DataFrame([
    [100, 90, 80],
    [100, 99, 88],
    [99, 91, 79],
  ], columns=['하나', '둘', '셋'])
  io = BytesIO()  # 바이너리 버퍼
  df.to_excel(io, index=None)
  io.seek(0)
  # pip install openpyxl
  filename = quote('pandas_csv.xlsx')
  response = HttpResponse(io, content_type='application/vnd.ms-excel')
  response['Content-Disposition'] = "attachment; filename={}".format(filename)
  return response

from django.shortcuts import redirect
def get_redirect1(request):
  #return redirect('/blog') # 목록 페이지 경로
  #return redirect('blog:index')  # 목록 페이지 경로 name
  #return redirect('/blog/2')
  return redirect('blog:detail', post_id=2)

def get_redirect2(request):
  return redirect('http://google.com')

source/14_django/ch03_orm/student/views.py
from django.shortcuts import render
from student.models import Student
# Create your views here.
def index(request):
    students = Student.objects.all()
    return render(request,
                  'student/list.html',
                  {'students':students})

source/14_django/ch03_orm/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        rel="stylesheet">
  {% load static %}
  <link href="{% static 'img/brand.png' %}" rel="icon">
  <link href="{% static 'css/ex.css' %}" rel="stylesheet">
  <title>{% block title %}제목{% endblock %}</title>
</head>
<body>
  <div class="p-5 mb-4 bg-body-tertiary rounded-3">
    {% block content %}
      기본 컨텐츠 영역
    {% endblock %}
  </div>
  {% include "footer.html" with year=2025 %}
</body>
</html>

source/14_django/ch03_orm/blog/templates/blog/detail.html
{% extends "base.html" %}
{% block title %}{{post.id}}번 post{% endblock %}
{% block content %}
  {% if post %}
    <h3>{{post.id}}.{{post.title}}</h3>
    <p>
      {{post.content}}
      <span>{{post.create_at}}</span>
      <span>{{post.update_at}}</span>
    </p>
    <h4>댓글 : {{ post.comment_set.all | length }}개</h4>
    {% for comment in post.comment_set.all %}
      <h6>
        {{comment.message}}
        <span>
          by {{comment.author}} at {{comment.update_at}}
        </span>
      </h6>
    {% endfor %}
    <h4>Tags</h4>
    {% for tag in post.tags.all %}
      <b>#{{tag.name}}</b>
    {% empty %}
      <h6>등록된 태그가 없습니다</h6>
    {% endfor %}
  {% else %}
    <p>No post</p>
  {% endif %}
  <button class="btn btn-primary"
      onclick="location='{% url 'blog:index' %}'">
    목록
  </button>
{% endblock %}

source/14_django/ch03_orm/blog/templates/blog/index.html
{% extends "base.html" %}
{% block title %}Welcome Page{% endblock %}
{% block content %}
  {% if post_list %}
    <ul>
    {% for post in post_list %}
      <li>
<!--        <a href="/blog/{{post.id}}/">{{post.id}}.{{post.title}}</a>-->
        <a href="{% url 'blog:detail' post.id %}">{{post.id}}.{{post.title}}</a>
        [{{ post.comment_set.all | length}}개 댓글]
        [{{post.tags.all | length}}개 태그]
      </li>
    {% endfor %}
    </ul>
  {% else %}
    <p>No posts are available.</p>
  {% endif %}
  <button class="btn btn-primary" onclick="location='{% url 'blog:json' %}'">
    json보기
  </button>
  <button class="btn btn-primary" onclick="location='{% url 'blog:excel' %}'">
    excel다운로드
  </button>
  <button class="btn btn-primary" onclick="location='{% url 'blog:csv' %}'">
    csv다운로드
  </button>
  <button class="btn btn-primary" onclick="location='{% url 'blog:csvexcel' %}'">
    csvexcel다운
  </button>
  <button class="btn btn-primary" onclick="location='{% url 'blog:redirect1' %}'">
    blog상세보기
  </button>
  <button class="btn btn-primary" onclick="location='{% url 'blog:redirect2' %}'">
    구글로가기
  </button>
{% endblock %}

source/14_django/ch03_orm/blog/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>
    /* * * * * footer * * * * * */
    footer{
        width:1000px; margin:5px auto;
        height: 150px;
        overflow: hidden;
    }
    footer div:last-child{
        height:50px; line-height:50px; text-align:center;
        background-color:black;
        color:white;
    }
  </style>
  <title>Title</title>
</head>
<body>
  <footer>
    <div class="copyright">{{ year }}Copyright ⓒ Joeun System Corp. All rights reserved.</div>
  </footer>
</body>
</html>