source/14_django/myproject/article/urls.py
from django.urls import path
from . import views
'''
/article/ => article_list
/article/new => article추가(article_new)
/article/1/detail => 1번 article 상세보기(article_detail)
/article/1/edit => 1번 article 수정(article_edit)
/article/1/delete => 1번 article 삭제(article_delete)
'''
app_name = "article"
urlpatterns = [
  path("", views.article_list, name="list"),
  path("new/", views.article_new, name="new"),
  path("<int:pk>/detail", views.article_detail, name='detail'),
  path("<int:pk>/edit/", views.article_edit, name="edit"),
  path("<int:pk>/delete/", views.article_delete, name="delete"),
]

source/14_django/myproject/blog/urls.py
from django.urls import path, register_converter
from . import views
from .converters import CodeConverter

register_converter(CodeConverter, "dddd")

app_name  = "blog" # 앱이름 사용
urlpatterns = [
    path("", views.index, name="index"),
    # localhost:8000/blog/1
    # path("<int:post_id>/", views.detail, name="detail") # int 컨버터를 사용
    path("<dddd:post_id>/", views.detail, name="detail"),
    path("json/", views.json_test, name="json"),
    path("excel/", views.excel_download, name="excel"),
    path("csv/", views.pandas_csv_download, name="csv"),
    path("csvexcel/", views.pandas_excel_download, name='csvexcel'),
    path("redirect1/", views.get_redirect1, name='redirect1'),
    path("redirect2/", views.get_redirect2, name='redirect2'),
]

source/14_django/myproject/book/urls.py
from django.urls import path
from . import views
'''
/book/ => book_list
/book/new => book추가(book_new)
/book/1/edit => 1번 article 수정(book_edit)
/book/1/delete => 1번 article 삭제(book_delete)
'''
app_name = "book"
urlpatterns = [
  path("", views.book_list, name="list"),
  path("new/", views.book_new, name="new"),
  path("<int:pk>/edit/", views.book_edit, name="edit"),
  path("<int:pk>/delete/", views.book_delete, name="delete"),
]

source/14_django/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", lambda r : redirect("blog:index")),
    path("blog/", include("blog.urls")),
    path("book/", include("book.urls")),
    path("article/", include("article.urls")),
    # path("file/", include("filetest.urls")),
    path("accounts/", include("accounts.urls")),
]
# 사용자가 업로그한 파일(MEDIA_ROOT)을 url(MEDIA_URL)과 연결
# 장고는 static은 자동 연결해 주나, media는 개발자가 연결
from django.conf.urls.static import static
from . import settings
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

source/14_django/myproject/myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
  <style>

  </style>
  {% load static %}
  <link href="{% static 'img/brand.png' %}" rel="icon">
  <link href="{% static 'css/ex.css' %}" rel="stylesheet">
  <title>{% block title %}제목{% endblock %}</title>
  <script src="//code.jquery.com/jquery-2.2.4.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  {%include "header.html"%}
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  {% include "footer.html" with year=2025 %}
</body>
</html>

source/14_django/myproject/myproject/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>
    /* * * * * footer * * * * * */
    footer{
        margin:5px auto;
        height: 150px;
        overflow: hidden;
    }
    footer div:last-child{
        height:50px; line-height:50px; text-align:center;
        background-color:black;
        color:white;
        position: absolute;
        bottom: 0;
        width:100%;
    }
  </style>
  <title>Title</title>
</head>
<body>
  <footer>
    <div class="copyright">{{ year }}Copyright ⓒ Joeun System Corp. All rights reserved.</div>
  </footer>
</body>
</html>

source/14_django/myproject/myproject/templates/header.html
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="{%if request.path == '/article/'%}active{%endif%}"><a href="{% url 'article:list' %}">Home</a></li>
                <li class="{%if request.path == '/blog/'%}active{%endif%}"><a href="{% url 'blog:index' %}">Blog</a></li>
                <li class="{%if request.path == '/book/'%}active{%endif%}"><a href="{% url 'book:list' %}">Book</a></li>
                <li><a href="/admin">Admin</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if not user.is_authenticated %}
                {% comment %} 로그인상태가 아닐때 {% endcomment %}
                    <li><a href="{%url 'signup'%}">회원 가입 </a> </li>
                    <li><a href="{%url 'login'%}?next={{request.path}}">로그인</a></li>
                {% else %}
                    <li><a href="#">{{user}}님</a></li>
                    <li><a href="{%url 'profile'%}">프로필</a> </li>
                    <li><a href="{%url 'logout'%}?next={{request.path}}">로그아웃</a> </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>